# Generated by Django 4.1.1 on 2023-02-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=20)),
                ('ename', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('ephone', models.IntegerField(max_length=20)),
            ],
        ),
    ]
